demo_login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'demo_login'
urlpatterns = [
    path('',views.index,name='index'),
    path('home/',views.home,name='home'),
    path('signup/',views.usersignup,name='signup'),
    path('logout/',views.userlogout,name='logout'),
    path('login/',views.userlogin,name='login'),
    path('add/',views.add,name='add'),
    path('specificsupdate/<int:id>',views.update,name='update'),
    path('specificsdelete/<int:id>',views.delete,name='delete'),
    path('modal/',views.modal,name='modal'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('loginapp/', include('demo_login.urls')),
    path('userlogin/', include('user_login.urls')),
    path('admin/', admin.site.urls),
]

user_login/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'todouser'
urlpatterns = [
   path('',views.userLogin,name='login'),
   path('logout/',views.userLogout,name='logout'),
   path('signup/',views.userSignup,name='signup'),
   path('index/',views.index,name='index')
]

demo_login/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)

user_login/models.py
from django.db import models

# Create your models here.

demo_login/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import Todo
# Create your views here.
def userlogin(request):
    if request.method=='POST':
        uname = request.POST['uname']
        pass1 = request.POST['pass1']
        user = authenticate(username=uname,password=pass1)
        if user:
            login(request,user)
            return redirect('demo_login:home')
    return render(request,'demo_login/login.html')
    

def userlogout(request):
    logout(request)
    return redirect('demo_login:login')
    

def usersignup(request):
    if request.method=='POST':
        uname = request.POST['uname']
        email = request.POST['mail']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        if(pass1==pass2):
            user = User.objects.create_user(uname,email,pass1)
            user.save()
            return redirect('demo_login:login')
    return render(request,'demo_login/signup.html',{})


def home(request):
    try:
        if(request.user.is_authenticated):
            print(1)
            return render(request,'demo_login/home.html',{'todo_list':request.user.todo_set.all()})
        return redirect('demo_login:login')
    except:
        return redirect('demo_login:login')


def index(request):
    return render(request,'demo_login/index.html')

def add(request):
    if request.method=='POST':
        title = request.POST['title']
        description = request.POST['desc']
        todo = Todo(title=title,description=description,user=request.user)
        todo.save()
        return redirect('demo_login:home')
    return redirect('demo_login:index')

def update(request,id):
    if request.method=='POST':
        title = request.POST['title']
        description = request.POST['desc']
        todo = Todo.objects.get(pk=id)
        todo.title=title
        todo.description=description
        todo.save()
        return redirect('demo_login:home')
    todo = Todo.objects.get(pk=id)
    return render(request,'demo_login/update.html',{'todo':todo})

def delete(request,id):
    todo = Todo.objects.get(pk=id)
    todo.delete()
    return redirect('demo_login:home')

def modal(request):
    return render(request,'demo_login/modal.html')

user_login/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def userLogin(request):
    if request.method=='POST':
        username = request.POST['uname']
        password = request.POST['pass1']
        user = authenticate(username=username,password=password)
        if user:
            login(request,user)
            return redirect('todouser:index')
    return render(request,'user_login/login.html')

def userLogout(request):
    logout(request)
    return redirect('todouser:login')
    

def userSignup(request):
    if request.method=='POST':
        username = request.POST['uname']
        email = request.POST['mail']
        password1 = request.POST['pass1']
        password2 = request.POST['pass2']
        if password1==password2:
            user = User.objects.create_user(username,email,password1)
            user.save()
            return redirect('todouser:login')
    return render(request,'user_login/signup.html')
    

def index(request):
    if (request.user.is_authenticated):
        return render(request,'user_login/index.html')
    
    return redirect('todouser:login')
    

demo_login/templates/demo_login/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    {% include 'demo_login/navbar.html' %}
    
    {%if user.is_authenticated %}
        <h1 style="text-align: center; text-transform: uppercase; color:violet">Welcome {{user.username}}</h1>
        <form method="post" action="{% url 'demo_login:add' %}" class="container w-50 mt-5" >
            {% csrf_token %}
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title" name="title" required>
              </div>
              <div class="mb-3">
                <label for="desc" class="form-label">Description</label>
                <input type="text" class="form-control" id="desc" name="desc" required>
              </div>
              <button type="submit" class="btn btn-primary mb-3">Submit</button>
        </form>
        <table class="table table-success table-striped container">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
              </tr>
            </thead>
        {% for todo in todo_list %}
        <tbody>
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{todo.title}}</td>
              <td>{{todo.description}}</td>
              <td>
                <a href="{% url 'demo_login:update' todo.id %}"><button type="button" class="btn btn-success">update</button></a>
                <a href="{% url 'demo_login:delete' todo.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
              </td>
            </tr>
        </tbody>
        {% endfor %}
        </table>
    {% else %}
        <h1>user not authenticated</h1>
    {% endif %}
</body>
</html>

demo_login/templates/demo_login/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% include 'demo_login/navbar.html' %}
    <div class="d-flex m-5 justify-content-center">
        <div class="card" style="width: 18rem;">
            <img src="https://cdn-icons-png.flaticon.com/512/2050/2050106.png" class="card-img-top mt-2 mx-auto"
                style="width: 200px;" alt="...">
            <div class="d-grid gap-2 col-4 mx-auto my-2">
                <a href="{% url 'demo_login:login' %}"><button class="btn btn-primary" type="button">Login</button></a>
            </div>
        </div>
        <div class="card mx-2" style="width: 18rem;">
            <img src="https://cdn-icons-png.flaticon.com/512/1208/1208635.png"  style="width: 200px;" class="card-img-top mt-2 mx-auto" alt="...">
            <div class="d-grid gap-2 col-4 mx-auto my-2">
                <a href="{% url 'demo_login:signup' %}"><button class="btn btn-primary" type="button">Signup</button></a>
            </div>
        </div>
    </div>

</body>

</html>

demo_login/templates/demo_login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
</head>
<body>
    {% include 'demo_login/navbar.html' %}
    <form method="post" action="{% url 'demo_login:login' %}" class="container w-50 mt-5" >
        {% csrf_token %}
        <div class="mb-3">
            <label for="uname" class="form-label">Username</label>
            <input type="text" class="form-control" id="uname" name="uname" required>
          </div>
          <div class="mb-3">
            <label for="Pass1" class="form-label">Password</label>
            <input type="password" class="form-control" id="pass1" name="pass1" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
</body>
</html>

demo_login/templates/demo_login/modal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'demo_login/m.css' %}" rel="stylesheet">

</head>

<body>
    
    <div id="mymodal" class="modal">

        <div class="modal_content">
            <span id="close" class="close">&times;</span>
            <form class="form">
                <div class="form_element">
                    <label>username</label>
                    <input type="text"><br>
                </div>
                <div class="form_element">
                    <label>Password</label>
                    <input type="text"><br>

                </div>

                <input type="submit">
            </form>
        </div>
    </div>
    <script src="{% static 'demo_login/main.js' %}" ></script>
</body>

</html>

demo_login/templates/demo_login/navbar.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Hello, world!</title>
</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'demo_login:index' %}">Todo App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'demo_login:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>

                </ul>
                <form class="d-flex">
                    {%if user.is_authenticated %}

                    <a href="{% url 'demo_login:logout' %}"><button class="btn btn-outline-success"
                            type="button">logout</button></a>
                    {%else%}
                    <button id="mybtn" class="btn btn-outline-success me-2" type="button">login</button>
                    <!-- <a href="{% url 'demo_login:login' %}"><button class="btn btn-outline-success me-2"
                            type="button">login</button></a> -->
                    <a href="{% url 'demo_login:signup' %}"><button class="btn btn-outline-success"
                            type="button">Signup</button></a>
                    {% endif%}
                </form>
            </div>
        </div>
    </nav>
    {% include 'demo_login/modal.html' %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>

demo_login/templates/demo_login/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
</head>

<body>
    {% include 'demo_login/navbar.html' %}

    <form method="post" action="{% url 'demo_login:signup' %}" class="container w-50 mt-5">
        {% csrf_token %}
        <div class="mb-3">
            <label for="uname" class="form-label">Username</label>
            <input class="form-control" id="uname" type="text" name="uname" required>
        </div>
        <div class="mb-3">
            <label class="form-label" for="mail">Email</label>
            <input class="form-control" id="mail" type="text" name="mail" required>
        </div>
        <div class="mb-3">
            <label for="pass1" class="form-label">Password</label>
            <input class="form-control" type="password" name="pass1" required>
        </div>
        <div class="mb-3">
            <label class="form-label" for="pass2">Confirm</label>
            <input class="form-control" type="password" name="pass2" required>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</body>

</html>

demo_login/templates/demo_login/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% include 'demo_login/navbar.html' %}
    <form method="post" action="{% url 'demo_login:update' todo.id %}" class="container w-50 mt-5" >
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" required value="{{todo.title}}">
          </div>
          <div class="mb-3">
            <label for="desc" class="form-label">Description</label>
            <input type="text" class="form-control" id="desc" name="desc" required value="{{todo.description}}">
          </div>
          <button type="submit" class="btn btn-primary mb-3">Submit</button>
    </form>
</body>
</html>

user_login/templates/user_login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome {{user.username}}</h1>
    <h1>welcome {{user.email}}</h1>
    <a href="{% url 'todouser:login' %}"><button>logout</button></a>
</body>
</html>

user_login/templates/user_login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" action="{% url 'todouser:login' %}">
        {% csrf_token %}
        <label>username</label>
        <input name="uname" type="text" required><br>
        <label>password</label>
        <input type="password" name="pass1" required><br>
        <input type="submit">
    </form>
</body>
</html>

user_login/templates/user_login/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" action="{% url 'todouser:signup' %}">
        {% csrf_token %}
        <label>username</label>
        <input name="uname" type="text" required><br>
        <label>email</label>
        <input name="mail" type="email" required><br>
        <label>password</label>
        <input name="pass1" type="password" required><br>
        <label>confirm</label>
        <input name="pass2" type="password" required><br>
        <input type="submit">
    </form>
</body>
</html>